enable-magisk-update = true

[YouTube]
build-mode = "module"
exclusive-patches = true
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
included-patches = "'Hide ads' 'Video ads' 'Enable slide to seek' 'Seekbar thumbnails' 'Disable auto captions' 'Hide video action buttons' 'Navigation buttons' 'Hide player overlay buttons' 'Hide endscreen cards' 'Hide info cards' 'Hide player flyout menu items' 'Disable rolling number animations' 'Hide Shorts components' 'Disable suggested video end screen' 'Custom player overlay opacity' 'Return YouTube Dislike' 'SponsorBlock' 'Change start page' 'Disable resuming Shorts on startup' 'Remove background playback restrictions' 'Bypass URL redirects' 'Remove tracking query parameter' 'Remember video quality' 'Playback speed' 'Restore old video quality menu'"
