enable-magisk-update = false
parallel-jobs = 1

[YouTube]
build-mode = "apk"
included-patches = "'Bypass URL redirects' 'Change start page' 'Custom player overlay opacity' 'Disable auto captions' 'Disable fullscreen ambient mode' 'Disable resuming Shorts on startup' 'Enable slide to seek' 'Force original audio' 'GmsCore support' 'Hide Shorts components' 'Hide ads' 'Hide end screen cards' 'Hide end screen suggested video' 'Hide info cards' 'Hide player flyout menu items' 'Hide player overlay buttons' 'Hide video action buttons' 'Navigation buttons' 'Playback speed' 'Remove background playback restrictions' 'Remove tracking query parameter' 'Remove viewer discretion dialog' 'Return YouTube Dislike' 'SponsorBlock' 'Video ads' 'Video quality' 'Open links externally' 'Hide layout components'"
exclusive-patches = true
version = "auto"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
