logging-to-file = false
enable-magisk-update = true
build-mindetach-module = false

[YouTube]
build-mode = "module"
included-patches = "disable-shorts-on-startup disable-auto-captions hdr-auto-brightness hide-ads hide-autoplay-button hide-crowdfunding-box hide-endscreen-cards hide-info-cards hide-player-overlay hide-watch-in-vr hide-watermark minimized-playback navigation-buttons old-video-quality-menu open-links-externally remember-video-quality return-youtube-dislike sponsorblock video-ads video-speed custom-video-buffer"
version = "auto"
exclusive-patches = true
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube/"
module-prop-name = "ytrv-magisk"
