logging-to-file = false
enable-magisk-update = true
build-mindetach-module = false

[YouTube]
build-mode = "module"
excluded-patches = ""
included-patches = "custom-video-buffer disable-auto-captions disable-shorts-on-startup hdr-auto-brightness hide-ads hide-autoplay-button hide-crowdfunding-box hide-endscreen-cards hide-get-premium hide-info-cards hide-watch-in-vr hide-watermark minimized-playback navigation-buttons old-quality-layout open-links-externally remember-video-quality return-youtube-dislike sponsorblock video-ads video-speed"
version = "auto"
exclusive-patches = true
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube/"
module-prop-name = "ytrv-magisk"
